version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8010:80"  # 映射到3000端口避免与其他服务冲突
    environment:
      # 构建时环境变量（如果需要）
      - NODE_ENV=production
    
    # 如果需要连接到后端服务，可以添加网络配置
    # networks:
    #   - app-network
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 重启策略
    restart: unless-stopped
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

# 如果需要连接到后端，可以创建外部网络
# networks:
#   app-network:
#     external: true

# 或者如果要与后端服务一起编排，可以这样配置：
# networks:
#   app-network:
#     driver: bridge
